 #ifndef HVC_CONFIG_H
 #define HVC_CONFIG_H

#define HEARTBEAT_TIME 1000
#define CMD_MSG_TIMEOUT 1000

#define PRECHARGE_MIN_TIME 1000
#define PRECHARGE_MAX_TIME 10000
#define PRECHARGE_PERCENT_DIF 5.0f

#endif